---
name: R-CMD-check
description: 'Run R CMD check on an R package repo'
inputs:
  github_dependencies:
    required: false
  token:
    required: false
runs:
  using: "composite"
  steps:
    - name: Deprecation Warning
      run: echo "::warning::[DEPRECATED VERSION] You are using v1, which is deprecated. Please upgrade to v2 using uclahs-cds/tool-R-CMD-check-action@v2"
      shell: bash
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::rcmdcheck
          any::devtools
          any::rmarkdown
        needs: check
    - run: Rscript "${{github.action_path}}/install.github.R" --packages="${{github.event.inputs.github_dependencies}}" --token="${{github.event.inputs.token}}"
      shell: bash
    - uses: r-lib/actions/check-r-package@v2
      with:
        args: 'c("--as-cran")'
        build_args: 'c("--compact-vignettes=gs+qpdf")'
    - name: Save built package and check results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: check
