---
name: R-CMD-check
description: 'Run R CMD check on an R package repo'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::rcmdcheck
          any::devtools
        needs: check
    - uses: r-lib/actions/check-r-package@v2
      with:
        args: 'c("--as-cran")'
        build_args: 'c("--compact-vignettes=gs+qpdf")'
