---
name: R-CMD-check
description: 'Run R CMD check on an R package repo'
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'latest'

    - name: Restore renv from cache
      uses: actions/cache@v4
      id: restore-renv
      with:
        path: ~/.cache/R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
        restore-keys: |
          ${{ runner.os }}-renv-

    - name: Install renv
      run: |
        Rscript -e 'if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")'
      shell: bash

    - name: Restore R package dependencies
      run: |
        Rscript -e "renv::init()"
        Rscript -e "renv::snapshot()"
        Rscript -e "renv::restore()"
      shell: bash

    - name: Install dev dependencies
      run: |
        Rscript -e "renv::install('pandoc')"
      shell: bash

    - name: Save updated renv cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/R/renv
        key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}

    - name: Run R CMD check
      run: |
        R CMD build .
        R CMD check --as-cran *.tar.gz
      shell: bash
