---
name: R-CMD-check
description: 'Run R CMD check on an R package repo'
inputs:
  github_dependencies:
    required: false
  token:
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: |
          any::rcmdcheck
          any::devtools
          any::rmarkdown
        needs: check
    - run: Rscript "${{github.action_path}}/install.github.R" --packages="${{github.event.inputs.github_dependencies}}" --token="${{github.event.inputs.token}}"
      shell: bash
    - run: R -e "print(names(grDevices::pdfFonts()))"
      shell: bash
    - run: R -e "print(names(grDevices::postscriptFonts()))"
      shell: bash
